# Dockerfile.backend.prod
FROM node:20-alpine AS builder
WORKDIR /app

# Copy only the package files first to cache dependencies
COPY backend/package*.json ./
RUN npm install --production

# Copy source code and build the backend application
COPY backend/ ./

ENV NODE_ENV=production
EXPOSE ${BACKEND_PORT}

# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# USER appuser

CMD ["npm", "run", "start"]
