# Dockerfile.backend.dev
FROM node:20-alpine
WORKDIR /app

# Copy package files first for caching
COPY backend/package*.json ./
RUN npm install

# Copy the rest of the source code
COPY backend/ ./

# Install nodemon globally for live reloading
RUN npm install -g nodemon


ENV NODE_ENV=development
EXPOSE ${BACKEND_PORT}

# Use nodemon to watch for changes and restart the backend
CMD ["nodemon", "--watch", ".", "--ignore", "logs", "--ignore", "dist", "--exec", "npm run start"]
