apiVersion: v1
kind: Service
metadata:
  name: campus-connect-backend-service
spec:
  selector:
    app: campus-connect-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
