apiVersion: v1
kind: ConfigMap
metadata:
  name: campus-connect-config
  namespace: default
data:
  HOST: "0.0.0.0"
  DOMAIN: "localhost"
  BACKEND_PORT: "3000"
  FRONTEND_PORT: "8080"
  WS_PORT: "3001"
  WS_PATH: "/ws"
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  MONGO_DB: "campusconnect_db"
  MONGO_URI: "mongodb://mongo:27017/campusconnect_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "super_secret_password"
  REDIS_URI: "redis://redis:6379"
  SESSION_SECRET: "super_secret_key"
  LOG_LEVEL: "info"
  # Update the backend upstream to match the Kubernetes service name
  NGINX_BACKEND_UPSTREAM: "campus-connect-backend-service:3000"
  NGINX_FRONTEND_UPSTREAM: "campus-connect-frontend-service:80"
