apiVersion: v1
kind: ConfigMap
metadata:
  name: campus-connect-config
  namespace: default
data:
  # Original values
  HOST: "0.0.0.0"
  DOMAIN: "localhost"
  BACKEND_PORT: "3000"
  FRONTEND_PORT: "8080"
  WS_PORT: "3001"
  WS_PATH: "/ws"
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  MONGO_DB: "campusconnect_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "super_secret_password"
  SESSION_SECRET: "super_secret_key"
  LOG_LEVEL: "info"
  NGINX_BACKEND_UPSTREAM: "campus-connect-backend-service:3000"
  NGINX_FRONTEND_UPSTREAM: "campus-connect-frontend-service:80"
  ENCRYPTION_KEY: "super_secret"
  
  # New keys (from configuration.ts)
  NODE_ENV: "development"         # Change to "production" in production
  SITE_DOMAIN: "http://localhost"        # Use this as your site domain (mirroring DOMAIN)
  API_PREFIX: "api"               # Global API prefix
  PORT: "3000"                    # Use the same as BACKEND_PORT to maintain consistency
  REST_API_BASE: "api"           # Base path for REST API endpoints
  SESSION_LIFETIME: "86400000"    # Session lifetime in ms (default is 1 day)
  COOKIE_SECURE: "false"          # Set "true" in production with HTTPS
  COOKIE_SAME_SITE: "strict"         # Can be "lax", "strict", or "none"
  CORS_ORIGIN: "*"               # Allow all origins; adjust as needed for security
  NGINX_NODE_PORT: "80"           # For external access through NGINX (if needed)
