apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-connect-frontend
  labels:
    app: campus-connect-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campus-connect-frontend
  template:
    metadata:
      labels:
        app: campus-connect-frontend
    spec:
      containers:
      - name: frontend
        image: campus-connect-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: campus-connect-config
