apiVersion: v1
kind: Service
metadata:
  name: campus-connect-frontend-service
spec:
  selector:
    app: campus-connect-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
